name: Docker Image CI for Ubuntu with Cuda

on:
  push:
    tags:
      - '*-cu*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
#    - name: Login to Aliyun Docker Registry
#      uses: docker/login-action@v3
#      with:
#        registry: registry.cn-hongkong.aliyuncs.com
#        username: ${{ secrets.ALIYUN_USERNAME }}
#        password: ${{ secrets.ALIYUN_PASSWORD }}
    - name: Check Github Tag
      id: checker
      run: |
        UBUNTU_VERSION=`echo ${GITHUB_REF#refs/tags/} | awk -F '-cu' '{print $1}'`
        CUDA_VERSION=`echo ${GITHUB_REF#refs/tags/} | awk -F '-cu' '{print $2}'`
        echo "ubuntu version:${UBUNTU_VERSION},cuda version:${CUDA_VERSION}"
        echo "UBUNTU_VERSION=$UBUNTU_VERSION" >> "$GITHUB_ENV"
        echo "CUDA_VERSION=$CUDA_VERSION" >> "$GITHUB_ENV"
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ubuntu-desktop
        file: ubuntu-desktop/${{env.UBUNTU_VERSION}}/Dockerfile
        platforms: linux/amd64
        build-args: |
          BASE_IMAGE=nvidia/cuda:${{env.CUDA_VERSION}}-runtime-ubuntu${{env.UBUNTU_VERSION}}
        push: true
        tags: |
          codeboy-zuo/docker-ubuntu22.04-desktop:${{env.UBUNTU_VERSION}}-cu${{env.CUDA_VERSION}}
#          registry.cn-hongkong.aliyuncs.com/gezp/ubuntu-desktop:${{env.UBUNTU_VERSION}}-cu${{env.CUDA_VERSION}}
